version: "3.9"
services:
  workspace:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-18-bullseye
    volumes:
      - ../:/work
    working_dir: /work
    command: sleep infinity
    depends_on:
      - mongo
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports: ["27017:27017"]
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:

