name: UAT

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  uat:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6
        ports: ["27017:27017"]
    env:
      NODE_ENV: test
      MONGODB_URI: mongodb://127.0.0.1:27017/symbi_uat
      JWT_SECRET: test-secret
      CORS_ORIGINS: http://localhost:3000
      METRICS_TOKEN: test-metrics
      # Optional vendor keys if you want full LLM tests:
      # OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 18 }

      - name: Install backend
        run: cd backend && npm ci

      - name: Start backend
        run: |
          cd backend
          nohup npm run dev >/tmp/backend.log 2>&1 &
          for i in {1..60}; do
            curl -fsS http://localhost:5000/healthz && break
            sleep 1
          done
          curl -fsS http://localhost:5000/metrics -H "Authorization: Bearer $METRICS_TOKEN" >/dev/null

      - name: Smoke (metrics included)
        run: |
          chmod +x tools/smoke.sh
          API_BASE=http://localhost:5000 ./tools/smoke.sh

      - name: Newman (optional – requires jwt & conv)
        if: ${{ vars.UAT_JWT != '' && vars.UAT_CONV_ID != '' }}
        run: |
          npm i -g newman
          newman run tools/SYMBI_Postman_Collection.json \
            --env-var baseUrl=http://localhost:5000 \
            --env-var jwt="${{ vars.UAT_JWT }}" \
            --env-var convId="${{ vars.UAT_CONV_ID }}" \
            --env-var webhookSecret="${{ secrets.WEBHOOK_SECRET }}"
            
      - name: Upload backend logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with: { name: backend-logs, path: /tmp/backend.log }