import { z } from 'zod';
export declare const ClassificationLevel: any;
export type ClassificationLevel = z.infer<typeof ClassificationLevel>;
export declare const TLPLevel: any;
export type TLPLevel = z.infer<typeof TLPLevel>;
export declare const MessageEnvelopeSchema: any;
export type MessageEnvelope = z.infer<typeof MessageEnvelopeSchema>;
export declare const AgentManifestSchema: any;
export type AgentManifest = z.infer<typeof AgentManifestSchema>;
export declare const ToolFunctionSchema: any;
export type ToolFunction = z.infer<typeof ToolFunctionSchema>;
export declare const AGENT_ROLES: {
    readonly OVERSEER: "overseer";
    readonly INTEL_ANALYST: "intel_analyst";
    readonly FIELD_COMMANDER: "field_commander";
    readonly CYBER_SECURITY: "cyber_security";
    readonly RED_TEAM: "red_team";
    readonly OSINT_HARVESTER: "osint_harvester";
    readonly LOGISTICS: "logistics";
    readonly PROTOCOL_OFFICER: "protocol_officer";
    readonly NEGOTIATOR: "negotiator";
};
export type AgentRole = typeof AGENT_ROLES[keyof typeof AGENT_ROLES];
export declare const MessageResponseSchema: any;
export type MessageResponse = z.infer<typeof MessageResponseSchema>;
export declare const AuditLogEntrySchema: any;
export type AuditLogEntry = z.infer<typeof AuditLogEntrySchema>;
